import React from 'react';
import { Container, Row, Col, Button, Modal, ModalHeader, ModalBody, ModalFooter } from 'reactstrap';
import '../css/Project.css';

const items = [
    {
        src: 'https://farm8.staticflickr.com/7174/6479325377_ba1fa998bc_b.jpg',
        altText: 'Real Chatting',
        title: "Real Chatting",
        usedLanguage: "NodeJS, Socket, Javascript, HTML, Jade, CSS, MySQL",
        purpose: "As a first project, I wanted to create a real time application. One of typical real times was chatting service.",
        description: "In order to communicate in real time, I was supposed to know how to deal with socket. Once I looked over about socket, I figured out I need to use socket.io module in nodejs. Through 'socket.on and socket.emit', I made up to represent the message from A user to B user's computer simultaneously. Also, by using session and MySQL, the record of user who has signed up and logged is kept until program ends.",
        hardPoint: "confusion between 'on & emit' from server and user",
        overcome: "from - emit / to - on -> Through io.emit(eventName, variable) in server, user is able to get socket.on(eventName, (variable) => { ~ }. In other words, by using emit & on, server and user can get each data (variable) with same event name in real time. For example, io.emit('new message', {msg:data, nick:socket.nickname}); -> socket.on('new message', function(data){$('#chat').append(data.nick + ' : ' + data.msg + '\n');",
        url: "https://github.com/Cool-Hongsi/Real-Chat-Version-2"
    },
    {
        src: 'https://farm1.staticflickr.com/183/407615640_8e3d6381fb_m.jpg',
        altText: 'School Course',
        title: "School Course",
        usedLanguage: "NodeJS, Javascript, Jade, CSS, PostgreSQL, MongoDB, GoogleAPI",
        purpose: "In order to provide Seneca students with information of every course",
        description: "As a team project with college friends, I created school course application which focuses on user interface. I put login and signup functions as well as used two types of databases in order to store course information in PostgreSQL and user information in MongoDB. Also, I made an effort to reflect a convenient way for user. For this reason, I considered well-organized design and used Google Passport API to make login easily via google account. In order to build up security, all passwords are generated by bcrypt and salt.",
        hardPoint: "Google Passport API, Connection with two databases.",
        overcome: "Google Passport API (I was supposed to be good at using passport module with authentificate. Once I studied for that module, I got an key to used API provided google and applied it to my application. And I used serialize and deserialize as well as declared session to store user information (signup). Connection with two databases (The way for connection to each database was different respectively. To connect, I use sequelize module for PostgreSQL and mongoose module for MongoDB. After setting up two databases in NodeJS with MVC style, to read information, I used pgAdmin for PostgreSQL and Robo3T (with mlab) for MongoDB.",
        url : "https://github.com/Cool-Hongsi/Seneca-Course-Application"
    },
    {
        src: 'http://maplecrm.com/blog/wp-content/uploads/2015/02/hr_employees_management1.jpg',
        altText: 'Manage Info v1',
        title: "Manage Info v1",
        usedLanguage: "Javascript(HandleBarJS), CSS, BootStrap, NodeJS, MongoDB, Heroku",
        purpose: "As one of the school projects, I created the web application to manage information with MongoDB.",
        description: "To experience MVC style (M - MongoDB, V - ejs (HandleBarJS), C - NodeJS), I created web application which can manage information. Particularly, it was interesting point for me to use ejs module with setting up .hbs engine since I can use for loop or if condition in frontend page contrary to general HTML. Also, through multer function, I can deal with uploading image conveniently. I distinguished a lot of routers as its role and communicate with MongoDB by using Promise asynchronous way.",
        hardPoint: "Asynchronous (Promise), HandleBar",
        overcome: "Asynchronous (It was unfamiliar way for me in dealing with data. As the result of struggling to understand it, I understood it as well as how to use it (resolve calls then, reject calls catch). (NodeJS is operated by single thread and asnychronous way. It takes up less memory than other server-side language as well as process the tasks with event function)). HandleBar (To use HandleBar, it is required to declare in defaultLayout (main.ejs) firstly with engine, main.ejs incorporates all other handlebar files. Also, it enable to use variable, for loop and if condition etc).",
        url : "https://github.com/Cool-Hongsi/WEB322-Project"
    },
    {
        src: 'http://maplecrm.com/blog/wp-content/uploads/2015/02/hr_employees_management1.jpg',
        altText: 'Manage Info v2',
        title: "Manage Info v2",
        usedLanguage: "ReactJS, ES6 Grammer",
        purpose: "This is the upgraded version of Manage Info v1 by using ReactJS.",
        description: "I studied replacing Manage Info v1 with v2. From this project, I figured out the HandleBarJS to show the data in frontend page could be replaced as ReactJS (The role of View).",
        hardPoint: "Use axios, Understanding (component, props, state)",
        overcome: "Axios (Axios enable to receive json data from API. Even though I was familiar with 'fetch' method, I realized axios and fetch have same role from this project), Understanding (As the position of component, web page can be changed easily and effectively. Also, through props and state, it enables to transfer variable between parent component and child component (with function as well)).",
        url : "https://github.com/Cool-Hongsi/React-Manage-Employee"
    },
    {
        src: 'https://cdn-resources.ableton.com/resources/af/4e/af4e549b-fca2-43c0-9fa0-1f1e085236d8/drum_booth.jpg',
        altText: 'Drum Machine',
        title: "Drum Machine",
        usedLanguage: "ReactJS, NodeJS, BootStrap, Heroku",
        purpose: "One of the projects in Free Code Camp",
        description: "Make the drum sound web application. Not only clicking button, but also typing keyboard will create the drum sound. Although it is small project, I was able to learn a lot from this project such as combine ReactJS and NodeJS (setting up proxy server), send drum sound information from one of routers in NodeJS and receive the data in ReactJS by using fetch method, addEventListener with DOM ('keydown')",
        hardPoint: "Set up button by using map method with each property, Call function in parent component from child component",
        overcome: "Map method has a variety of advantages. Particularly, it enable to make long long source code breifly. Also, as approaching each property, I can set up each index of big array. For example, {this.state.items.map((el) => { return( <span key={el.id}> <audio id={el.keyTrigger} src={el.url}></audio>... In the case of call parent function, when I call child component, I need to set up the code like <Child changeBackColor={this.changeBackColor} /> and changeBackColor function should be delcared in parent component. After then, in child component, use {this.props.changeBackColor}.",
        url : "https://github.com/Cool-Hongsi/Play-Drum"
    },
    {
        src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFcRy79_ynO8mvwb5AM7UxcLkjMlEmspMVP74HYk9vBWN3jX-L',
        altText: 'Shopping Cart',
        title: "Shopping Cart",
        usedLanguage: "MVC (ReactJS, NodeJS, MongoDB), REST API",
        purpose: "Working on it",
        description: "",
        hardPoint: "",
        overcome: "",
        url : "/"
    },
    {
        src: 'https://pbs.twimg.com/profile_images/925333528325296129/Qgw0d8Kv_400x400.jpg',
        altText: 'This Portfolio',
        title: "This Portfolio",
        usedLanguage: "ReactJS, Green Sock, Bootstrap, CSS",
        purpose: "I wanted to create new portfolio (already have previous version) by using ReactJS and CSS.",
        description: "Particularly, in order to create responsive application, I set Grid and media as the size of each device. Also, without using template, I considered and created my own design and frame by myself.",
        hardPoint: "Setting up media size was a kind of hard point for me since I need to appoint each style as the size of media respectively. Also, in using Green Sock, I studied TweenMax, Power2 to put unique effect.",
        overcome: "Whenever I got stuck in designing, I looked over some of youtube coding materials and refered to it. I could realize that many things can be much better through even small code.",
        url : "/"
    }
];

export default class Project extends React.Component{
    constructor(props) {
        super(props);
        this.state = {
          modal: false,
          data: {
              src: '',
              altText: '',
              title: '',
              usedLanguage: '',
              url : '',
              purpose : '',
              description : '',
              hardPoint : '',
              overcome : ''
          }
        };

        this.turnOffToggle = this.turnOffToggle.bind(this);
        this.changeToggle = this.changeToggle.bind(this);        
    }
    
    turnOffToggle(){
        this.setState({
            modal: !this.state.modal
        });
    }

    changeToggle(el) {
        this.setState({
            modal: !this.state.modal,
            data: {
                src: el.src,
                altText: el.altText,
                title: el.title,
                usedLanguage: el.usedLanguage,
                url: el.url,
                purpose: el.purpose,
                description: el.description,
                hardPoint: el.hardPoint,
                overcome: el.overcome
            }
        });
    }

    render(){
        const projectList = items.map((el) => {
            return(
                <Col xs="12" sm="6" md="3" lg="3" xl="3">
                    <div className="box">
                        <div className="imgBox">
                            <img src={el.src} alt={el.altText}/>
                        </div>
                        <div className="details">
                            <div className="content">
                                <h2>{el.title}</h2><br/>
                                <Button className="descBtn" color="warning" onClick={() => this.changeToggle(el)}>Detail</Button>
                            </div>
                        </div>
                    </div>
                </Col>
            )
        })
        return(
            <div id="project">
                <Container>
                    <Row>
                        {projectList}
                    </Row>
                </Container>
                <Modal className="modal-body" isOpen={this.state.modal}>
                    <ModalHeader>{this.state.data.title}</ModalHeader>
                    <ModalBody>
                        <span className="emphasis">[ Used ] : </span>{this.state.data.usedLanguage}<br/><br/>
                        <span className="emphasis">[ Purpose ] : </span>{this.state.data.purpose}<br/><br/>
                        <span className="emphasis">[ Description ] : </span>{this.state.data.description}<br/><br/>
                        <span className="emphasis">[ Hard Point ] : </span>{this.state.data.hardPoint}<br/><br/>
                        <span className="emphasis">[ Overcome ] : </span>{this.state.data.overcome}
                    </ModalBody>
                    <ModalFooter>
                        <a href={this.state.data.url} rel="noopener noreferrer" target="_blank"><Button outline color="danger">GitHub</Button>{' '}</a>
                        <Button outline color="secondary" onClick={this.turnOffToggle}>Cancel</Button>
                    </ModalFooter>
                </Modal>
            </div>
        )
    }
}