import React from 'react';
import { Container, Row, Col, Button, Modal, ModalHeader, ModalBody, ModalFooter } from 'reactstrap';
import '../css/Project.css';

const items = [
    {
        src: 'https://farm8.staticflickr.com/7174/6479325377_ba1fa998bc_b.jpg',
        altText: 'Real Chatting',
        title: "Real Chatting",
        usedLanguage: "NodeJS, Socket, Javascript, HTML, Jade, CSS, MySQL",
        purpose: "As a first project, I wanted to create a real time application. One of typical real times was chatting service.",
        description: "In order to communicate in real time, I was supposed to know how to deal with socket. Once I looked over about socket, I figured out I need to use socket.io module in nodejs. Through 'socket.on and socket.emit', I made up to represent the message from A user to B user's computer simultaneously. Also, by using session and MySQL, the record of user who has signed up and logged is kept until program ends.",
        hardPoint: "confusion between 'on & emit' from server and user",
        overcome: "from - emit / to - on -> Through io.emit(eventName, variable) in server, user is able to get socket.on(eventName, (variable) => { ~ }. In other words, by using emit & on, server and user can get each data (variable) with same event name in real time. For example, io.emit('new message', {msg:data, nick:socket.nickname}); -> socket.on('new message', function(data){$('#chat').append(data.nick + ' : ' + data.msg + '\n');",
        url: "https://github.com/Cool-Hongsi/Real-Chat-Version-2"
    },
    {
        src: 'https://farm1.staticflickr.com/183/407615640_8e3d6381fb_m.jpg',
        altText: 'School Course',
        title: "School Course",
        usedLanguage: "NodeJS, Javascript, Jade, CSS, PostgreSQL, MongoDB, GoogleAPI",
        purpose: "In order to provide Seneca students with information of every course",
        description: "As a team project with college friends, I created school course application which focuses on user interface. I put login and signup functions as well as used two types of databases in order to store course information in PostgreSQL and user information in MongoDB. Also, I made an effort to reflect a convenient way for user. For this reason, I considered well-organized design and used Google Passport API to make login easily via google account. In order to build up security, all passwords are generated by bcrypt and salt.",
        hardPoint: "Google Passport API, Connection with two databases.",
        overcome: "Google Passport API (I was supposed to be good at using passport module with authentificate. Once I studied for that module, I got an key to used API provided google and applied it to my application. And I used serialize and deserialize as well as declared session to store user information (signup). Connection with two databases (The way for connection to each database was different respectively. To connect, I use sequelize module for PostgreSQL and mongoose module for MongoDB. After setting up two databases in NodeJS with MVC style, to read information, I used pgAdmin for PostgreSQL and Robo3T (with mlab) for MongoDB.",
        url : "https://github.com/Cool-Hongsi/Seneca-Course-Application"
    },
    {
        src: 'http://maplecrm.com/blog/wp-content/uploads/2015/02/hr_employees_management1.jpg',
        altText: 'Manage Info v1',
        title: "Manage Info v1",
        usedLanguage: "Javascript(HandleBarJS), CSS, BootStrap, NodeJS, MongoDB, Heroku",
        purpose: "As one of the school projects, I created the web application to manage information with MongoDB.",
        description: "To experience MVC style (M - MongoDB, V - ejs (HandleBarJS), C - NodeJS), I created web application which can manage information. Particularly, it was interesting point for me to use ejs module with setting up .hbs engine since I can use for loop or if condition in frontend page contrary to general HTML. Also, through multer function, I can deal with uploading image conveniently. I distinguished a lot of routers as its role and communicate with MongoDB by using Promise asynchronous way.",
        hardPoint: "Asynchronous (Promise), HandleBar",
        overcome: "Asynchronous (It was unfamiliar way for me in dealing with data. As the result of struggling to understand it, I understood it as well as how to use it (resolve calls then, reject calls catch). (NodeJS is operated by single thread and asnychronous way. It takes up less memory than other server-side language as well as process the tasks with event function)). HandleBar (To use HandleBar, it is required to declare in defaultLayout (main.ejs) firstly with engine, main.ejs incorporates all other handlebar files. Also, it enable to use variable, for loop and if condition etc).",
        url : "https://github.com/Cool-Hongsi/WEB322-Project"
    },
    {
        src: 'http://maplecrm.com/blog/wp-content/uploads/2015/02/hr_employees_management1.jpg',
        altText: 'Manage Info v2',
        title: "Manage Info v2",
        usedLanguage: "ReactJS, ES6 Grammer",
        purpose: "This is the upgraded version of Manage Info v1 by using ReactJS.",
        description: "I studied replacing Manage Info v1 with v2. From this project, I figured out the HandleBarJS to show the data in frontend page could be replaced as ReactJS (The role of View).",
        hardPoint: "Use axios, Understanding (component, props, state)",
        overcome: "Axios (Axios enable to receive json data from API. Even though I was familiar with 'fetch' method, I realized axios and fetch have same role from this project), Understanding (As the position of component, web page can be changed easily and effectively. Also, through props and state, it enables to transfer variable between parent component and child component (with function as well)).",
        url : "https://github.com/Cool-Hongsi/React-Manage-Employee"
    },
    {
        src: 'https://i1.wp.com/itsblockchain.com/wp-content/uploads/2016/11/Screen-Shot-2015-04-28-at-3.31.23-pm.png?fit=738%2C340&ssl=1',
        altText: 'BlockCypher API',
        title: "BlockCypher API",
        usedLanguage: "Model (MySQL), View (ReactJS), Controller (NodeJS), bitcoinjs-lib, bitcoin-transaction, BootStrap",
        purpose: "Through BlockCypher API, Created web application which can retrieve the balance from a virtual wallet as well as set up payment system",
        description: "Process -> Generate random virtual wallet (Receive public address & private key) -> Achieve testnet bitcoin in virtual wallet via (https://tbtc.bitaps.com) -> Once the virtual wallet is charged by testnet bitcoin, the transaction record in virtual wallet will be added. (Can see the data by using BlockCypher API). -> Now, the user is able to view the record of wallet (including balance) -> Type another virtual wallet public address that the user would like to transfer bitcoin and amount -> The user is able to find out hex code and put the hex code into https://live.blockcypher.com/btc-testnet/pushtx -> Once the transaction is completed, the additional transaction record in virtual wallet will be added. -> As long as the user clicks 'Add Transaction', the record of transaction (Particularly, hash code) will be stored in MySQL -> As long as the user clicks 'Show Transaction', the record of transaction (All records) will be indicated on page",
        hardPoint: "Be familiar with how to control BlockCypher API.",
        overcome: "I login to the official website to see fundamental stuff and figured out how to handle the End point with GET and POST way. After receiving the data from user in frontend page, transfer data to backend page by using axios. After then, through API End point, I have access to API with req.body value.",
        url : "https://github.com/Cool-Hongsi/BlockCypher-API"
    },
    {
        src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFcRy79_ynO8mvwb5AM7UxcLkjMlEmspMVP74HYk9vBWN3jX-L',
        altText: 'Shopping Cart',
        title: "Shopping Cart",
        usedLanguage: "MVC (ReactJS, NodeJS, MongoDB), REST API, session, fetch, ES6",
        purpose: "I created this project in order to experience MVC design as well as understand server and client.",
        description: "I used ReactJS as frontend and NodeJS as backend. The reason why I used both of them is because I wanted to practice receiving the data from backend server and representing the data into frontend page. For this reason, as the standard of MVC design, I stored product list information into MongoDB and send the data from one of the routers in NodeJS. After then, I set up the proxy server as the same server of NodeJS, and receive the data by using fetch method in ReactJS. Also, represent data by using map and filter method (search bar as well) as ES6. In addition, I distinguished administrator version and user version in order to manage data and show data respectively with the standard of REST API. Particularly, as long as the user adds items in the shopping cart, the record is kept until program ends by using session.",
        hardPoint: "Interaction between ReactJS and NodeJS, Using Session",
        overcome: "It was hard for me to transfer data from backend to frontend, also, from frontend to backend. Once I send the data, even though it was easy to receive the data, the point was utilizing data as the requirement of roles. In order to get through it, I studied some of the sample code related to full-stack application and I could use fetch, map, filter, includes properly to utilize data. In using session, I got confused between cookie and session. Basicially, cookie stores data into file (no affect to memory), session stores data into server memory. For this reason, I decided to use session (much stronger than cookie in aspect of security), as long as the program does not end, made an effort to keep the cart data in server. Once the user click add button, one of property in session will be added about the product and send it to ReactJS and represent it by using fetch and map function",
        url : "https://github.com/Cool-Hongsi/shoppingcart"
    },
    {
        src: 'https://pbs.twimg.com/profile_images/925333528325296129/Qgw0d8Kv_400x400.jpg',
        altText: 'This Portfolio',
        title: "This Portfolio",
        usedLanguage: "ReactJS, Green Sock, Bootstrap, CSS",
        purpose: "I wanted to create new portfolio (already have previous version) by using ReactJS and CSS.",
        description: "Particularly, in order to create responsive application, I set Grid and media as the size of each device. Also, without using template, I considered and created my own design and frame by myself.",
        hardPoint: "Setting up media size was a kind of hard point for me since I need to appoint each style as the size of media respectively. Also, in using Green Sock, I studied TweenMax, Power2 to put unique effect.",
        overcome: "Whenever I got stuck in designing, I looked over some of youtube coding materials and refered to it. I could realize that many things can be much better through even small code.",
        url : "https://github.com/Cool-Hongsi/Hong-Portfolio"
    },
    {
        src: 'https://i.imgur.com/OvMZBs9.jpg',
        altText: 'To Do',
        title: "To Do",
        usedLanguage: "MERN (MongoDB, Express, ReactJS, NodeJS), MVC Design, REST API, Bootstrap",
        purpose: "In order to experience MERN stack development with REST API & Request information to backend by using axios",
        description: "Regarding languages, as the standard of MVC design, I used MERN stack (Model - MongoDB, View - ReactJS, Controller - NodeJS). Also, I set up routers in order to communicate between server and client effectively with REST API. In terms of contents, the landingpage is consisted of the lists of todo as well as some of button which has the functions to add, show, update and delete lists. By using react-router-dom, the page can add another component without page reloading (this.props.history.push & withRouter). Once the user click or do something for todo list, the data will transfer backend (NodeJS) and it would contact with database (MongoDB) and the reflected data will send to fronend page(ReactJS).",
        hardPoint: "Real-time reflection & Using axios with REST API & store state by using ES6",
        overcome: "I could realize that the real-time reflection does not work after the user does something in todo list. In order to solve it, I used componentWillUnmount() and set interval in order to request data from server every certain time. Also, as the standard of REST API, in setting up axios, it does not work properly, particularly, the params value. For this, I was able to figure out when the params are transferred to backend, the req.params value would became string. I immediately used parseInt(req.params.id) and made it up (axios code is axios.put(`/api/updateData/${this.props.id}`, {title : this.state.form.title, description : this.state.form.description}).then((res) => {). Finally, in order to store data into state by using ES6, I looked over official website for ReactJS and used the source code like ( this.setState({ form:{ ...this.state.form, [name]: value }});).",
        url : "https://github.com/Cool-Hongsi/ToDo"
    }
];

export default class Project extends React.Component{
    constructor(props) {
        super(props);
        this.state = {
          modal: false,
          data: {
              src: '',
              altText: '',
              title: '',
              usedLanguage: '',
              url : '',
              purpose : '',
              description : '',
              hardPoint : '',
              overcome : ''
          }
        };

        this.turnOffToggle = this.turnOffToggle.bind(this);
        this.changeToggle = this.changeToggle.bind(this);        
    }
    
    turnOffToggle(){
        this.setState({
            modal: !this.state.modal
        });
    }

    changeToggle(el) {
        this.setState({
            modal: !this.state.modal,
            data: {
                src: el.src,
                altText: el.altText,
                title: el.title,
                usedLanguage: el.usedLanguage,
                url: el.url,
                purpose: el.purpose,
                description: el.description,
                hardPoint: el.hardPoint,
                overcome: el.overcome
            }
        });
    }

    render(){
        const projectList = items.map((el) => {
            return(
                <Col xs="12" sm="6" md="3" lg="3" xl="3">
                    <div className="box">
                        <div className="imgBox">
                            <img src={el.src} alt={el.altText}/>
                        </div>
                        <div className="details">
                            <div className="content">
                                <h2>{el.title}</h2><br/>
                                <Button className="descBtn" color="warning" onClick={() => this.changeToggle(el)}>Detail</Button>
                            </div>
                        </div>
                    </div>
                </Col>
            )
        })
        return(
            <div id="project">
                <Container>
                    <Row>
                        {projectList}
                    </Row>
                </Container>
                <Modal className="modal-body" isOpen={this.state.modal}>
                    <ModalHeader>{this.state.data.title}</ModalHeader>
                    <ModalBody>
                        <span className="emphasis">[ Used ] : </span>{this.state.data.usedLanguage}<br/><br/>
                        <span className="emphasis">[ Purpose ] : </span>{this.state.data.purpose}<br/><br/>
                        <span className="emphasis">[ Description ] : </span>{this.state.data.description}<br/><br/>
                        <span className="emphasis">[ Hard Point ] : </span>{this.state.data.hardPoint}<br/><br/>
                        <span className="emphasis">[ Overcome ] : </span>{this.state.data.overcome}
                    </ModalBody>
                    <ModalFooter>
                        <a href={this.state.data.url} rel="noopener noreferrer" target="_blank"><Button outline color="danger">GitHub</Button>{' '}</a>
                        <Button outline color="secondary" onClick={this.turnOffToggle}>Cancel</Button>
                    </ModalFooter>
                </Modal>
            </div>
        )
    }
}